# アプリ名
name: gm_reviews_search_doctor_app

# 説明
description: "A new Flutter project."

# 公開先
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# バージョン
version: 1.0.1+2

# Dart SDK のバージョン
environment:
  sdk: ^3.7.0

# アプリで使うライブラリ
dependencies:
  flutter:
    sdk: flutter  # Flutter SDKを使うよという宣言
  flutter_dotenv: ^5.1.0  # envを使うためのパッケージ
  url_launcher: ^6.2.5  # URLを開くためのパッケージ
  logger: ^2.0.2
  path_provider: ^2.0.15  # ファイルの保存先を取得するためのパッケージ
  intl: ^0.18.1  # 日付や数値のフォーマットをするためのパッケージ

# ^1.3.0 の部分が「1.3.0 以上かつ 2.0.0 未満の最新版を使ってね」という意味のバージョン指定
  http: ^1.3.0
  cupertino_icons: ^1.0.8

# 開発中のテスト・分析用パッケージ
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter特有の設定（デザインやアセットなど）
flutter:
  uses-material-design: true

  # アセットの設定→ビルドに含めてもらうように設定
  assets:
    - .env
    - assets/icon/app_icon.png
    - assets/no_image_photo.png

# iconの設定
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

